name = "Cactus Plus"
license = "MIT"
licenselink = "https://github.com/nodejh/hugo-theme-cactus-plus/blob/master/LICENSE.md"
description = "A minimalistic and responsive theme for bloggers."
homepage = "https://github.com/nodejh/hugo-theme-simple"
tags = ["blog", "disqus", "duoshuo", "google analytics", "baidu tongji", "rss", "syntax highlighting", "tags", "categories"]
features = ["blog", "disqus", "duoshuo", "google analytics", "baidu tongji", "rss", "syntax highlighting", "tags", "categories"]
min_version = 0.10

[author]
  name = "nodejh"
  homepage = "https://github.com/nodejh"

[[original]]
  name = "Cactus"
  homepage = "https://themes.gohugo.io/cactus/"
  repo = "https://github.com/digitalcraftsman/hugo-cactus-theme"
