# Site settings
baseurl = "http://nodejh.com/"
languageCode = "zh-cn"
title = "nodejh"
theme = "hugo-theme-cactus-plus"
# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-84989670-1"
hasCJKLanguage = true

[params]
	name = "nodejh"
	description = "My Blog"
	bio = "Web Developer"

	enableRSS = true

	# Table of content
	enableToc = true

	# Disqus comment
	disqusShortname = "nodejh"
	# Enable disqus comment, true|false
	enableDisqus = true

	# Enable summary, true|false
	enableSummary = true
	# Use description replace summary, defalt false
	useDescriptionReplaceSummary = false

	# Enable Google Analytics
	enableGoogleAnalytics = true

	# Enable Baidu Analytics
	enableBaiduAnalytics = true
	# Baidu Analytics Code
	baiduAnalytics = '39843ea392201290bd6f76173d2e1633'

	# Add custom assets with their paths relative to the static folder
	customCSS = []
	customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	# Home text, default: 'Home'
	home = ""
	# About text, default: 'About'
	about = ""
	# Archive text, default: 'Archive'
	archive = ""
	#  Subscribe button Text, default: 'Subscribe'
	subscribe = ""

	# Pagination links
	# default: 'Older Posts'
	olderPosts = ""
	# default: 'Newer Posts'
	newerPosts = ""

	# show latest posts in single page
	showLatestPosts = true
	# Latest posts title, default: 'Read More'
	readMore = ""

	# default similar to: © Copyright 2017 ❤️ nodejh
	# 	nodejh is site name specified in params.name
	copyright = ""

	# Share
	enableShare = false
	# Enter optionally your twitter account
	twitterAccount = ""
	tweet = ""
	facebook = ""

	# 404 page
	title404 = ""
	subtitle404 = ""

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "font-awesome"
  # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
  socialIconStyle = ""

# Add additional social link entries underneath
[social]
	facebook-square = "https://www.facebook.com/nodejh"
	twitter-square = "https://www.twitter.com/nodejh"
	github-square = "https://www.github.com/nodejh"
