# Site settings
baseurl = "http://nodejh.com/"
languageCode = "zh-cn"
title = "nodejh"
theme = "hugo-theme-cactus-plus"
# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-84989670-1"

[params]
	name = "nodejh"
	description = "My Blog"
	bio = "To Be A Full Stack Developer"
	# Enter optionally your twitter account
	twitter = "nodejh"
	enableRSS = false

	# Disqus comment
	disqusShortname = "nodejh"
	# Disable disqus comments by set `enableDisqus = "false"`
	enableDisqus = false

	# Duoshuo comment
	duoshuoShortname = "nodejh"
	# Disable duoshuo comments by set `enableDuoshuo = "false"`
	enableDuoshuo = false

	enableGithubIssuesTips = false

	# Use description as title in single page, posts page and tags page.
	useDescriptionAsTitle = false

	# Add custom assets with their paths relative to the static folder
	customCSS = []
	customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = ""
	about = ""
	archive = ""
	subscribe = ""
	# Pagination links
	olderPosts = ""
	newerPosts = ""
	readMore = ""
	copyright = ""
	# Sharing options and author information in posts
	aboutAuthor = "I am so interesting."
	tweet = ""
	share = ""
	# 404 page
	title404 = ""
	subtitle404 = ""

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "font-awesome"
  # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
  socialIconStyle = ""


# Add additional social link entries underneath
[social]
	# For example: font-aswome-name = "your_social_url"
	facebook-square = "https://www.facebook.com/nodejh"
  twitter-square = "https://www.twitter.com/nodejh"
  github-square = "https://www.github.com/nodejh"
