# Site settings
baseurl = "http://nodejh.com/"
# HTML Language Code Reference, such as en, zh-cn
languageCode = "en"
title = "Blog Title"
theme = "hugo-theme-cactus-plus"
# Enter your tracking code to enable Google Analytics
googleAnalytics = "your_google_analytics_code"

[params]
	name = "Hugo"
	description = "Blog Description"
	bio = "Blog biology"
	# Enter optionally your twitter account
	twitter = "your_twotter"
	enableRSS = false

	# Disqus comment
	disqusShortname = "your_disqus_short_name"
	# Disable disqus comments by set `enableDisqus = "false"`
	enableDisqus = false

	# Duoshuo comment
	duoshuoShortname = "your_duoshuo_short_name"
	# Disable duoshuo comments by set `enableDuoshuo = "false"`
	enableDuoshuo = false

	enableGithubIssuesTips = false

	# Use description as title in single page, posts page and tags page.
	useDescriptionAsTitle = false

	# Enable googleAnalytics
	enableGoogleAnalytics = false

	# Enable baiduAnalytics
	enableBaiduAnalytics = false
	# Baidu Tongji Code
	baiduAnalytics = 'your_baidu_tongji_code'

	# Add custom assets with their paths relative to the static folder
	customCSS = []
	customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = ""
	about = ""
	archive = ""
	subscribe = ""
	# Pagination links
	olderPosts = ""
	newerPosts = ""
	readMore = ""
	copyright = ""
	# Sharing options and author information in posts
	aboutAuthor = "I am so interesting."
	tweet = ""
	share = ""
	# 404 page
	title404 = ""
	subtitle404 = ""

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "font-awesome"
  # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
  socialIconStyle = ""


# Add additional social link entries underneath
[social]
	facebook-square = "your_facebook_link"
  twitter-square = "your_twitter_link"
  github-square = "your_github_link"
